### ISSUE TITLE
Tasks persistence

### ISSUE THREAD

**Issue by serge-svg** [serge-svg/ironhack-labs-final-project#10]

**Comment by serge-svg** [comment]
## Todo

- [ ] Create a taskStore
- [ ] Create a tasks table in supabase
- [ ] Create a TasksListView and show a list of tasks
- [ ] Create a AddTasksView functional
- [ ] Delete task functionality
- [ ] Modify task functionality
